{"title": "Bread - Wikipedia, the free encyclopedia", "rank": 1, "snippet": "Bread is a staple food prepared from a dough of flour and water, usually by \nbaking. Throughout recorded history it has been popular around the world and is \none\u00a0...", "link": "https://en.wikipedia.org/wiki/Bread&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFggeMAQ&usg=AFQjCNH8fIXXYbsR5M7O2zlSZ2FvZGNCkQ", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Easy white bread | BBC Good Food", "rank": 2, "snippet": "Mix the flour, salt and yeast in a large bowl.\n ... Leave to rise for 1 hour until doubled in size or place in the fridge overnight.\n ... Bake for 25-30 mins until golden brown and the loaf sounds hollow when tapped underneath.", "link": "http://www.bbcgoodfood.com/recipes/2060/easy-white-bread&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFggnMAU&usg=AFQjCNGufNsjWSS6nw3E67gagFfy9niMIQ", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Bread | BBC Good Food", "rank": 3, "snippet": "There's nothing quite like warm, fresh-out-of-the-oven home-baked bread, as \nthese delectable recipes for how to make bread so comfortingly prove.", "link": "http://www.bbcgoodfood.com/recipes/collection/bread&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFggxMAY&usg=AFQjCNEd-CvkJC68ovuhJFgE8NJQyXULHw", "estimated": 324000000, "keyphrase": "bread"}
{"title": "BBC - Food - Bread recipes", "rank": 4, "snippet": "Sun-dried tomato and olive bread.\n ... Get started with Paul Hollywood's step-by-step white bread recipe or choose one of our other bread recipes for the perfect loaf.\n ... White bread should keep for 3-5 days; speciality breads, especially those containing fruit or grains, will go mouldy ...", "link": "http://www.bbc.co.uk/food/bread&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFgg1MAc&usg=AFQjCNHOGaDqkdC9edNhY_CIbTDHkOIf8w", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Basic Bread | Bread Recipes | Jamie Oliver Recipes", "rank": 5, "snippet": "A basic bread recipe for bakers at any level, perfect your loaf by practicing the \ntips, trick and techniques provided with Jamie's easy bread recipe.", "link": "http://www.jamieoliver.com/recipes/bread-recipes/basic-bread-recipe/&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFgg-MAg&usg=AFQjCNEmsPkgcguxDTnDLQiWBtQWQ8A24w", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Bread Recipes | Jamie Oliver", "rank": 6, "snippet": "Our bread recipes are a great way to get kids cooking; from bruschetta to rolls \nteach them how to make bread with a perfect dough recipe. Jamieoliver.com.", "link": "http://www.jamieoliver.com/recipes/bread-recipes/&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFghDMAk&usg=AFQjCNF_YvdBF-0Cxv7XsnWrhKZt_RjJQA", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Bread | Sainsbury's - Sainsburys.co.uk", "rank": 7, "snippet": "Buy Bread online from Sainsbury's, the same great quality, freshness and choice \nyou'd find in store. Choose from 1 hour delivery slots and collect Nectar points.", "link": "http://www.sainsburys.co.uk/shop/gb/groceries/bakery/bread&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFghQMA0&usg=AFQjCNFUqjqEPAmDnIUY7OXK5PtxgRLsng", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Bread | Paul Hollywood", "rank": 8, "snippet": "White Cob. If you are a novice baker you can use this recipe to make a basic loaf \nin a tin, although the quantities here provide more dough than you would need\u00a0...", "link": "http://paulhollywood.com/home/recipes/bread/&sa=U&ved=0ahUKEwjrjdHo9KHMAhUHCMAKHW64CtsQFghUMA4&usg=AFQjCNHqOf4o4_hYvAG0dob7i6dZFOLuAg", "estimated": 324000000, "keyphrase": "bread"}
{"title": "Bread Bread Bakery", "rank": 9, "snippet": "These wood oven baked breads are great for ripping, dipping, smearing and \ntoasting. They're structured enough for chefs to use as a platform for their own\u00a0...", "link": "http://www.breadbreadbakery.co.uk/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCBQwAA&usg=AFQjCNGJ2fikKq76hbySSWD_DOhp9glblw", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Real Bread Campaign", "rank": 10, "snippet": "Fighting for better bread in Britain and finding ways to make bread better for us, \nbetter for our communities and better for the planet.", "link": "http://www.realbreadcampaign.org/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCBcwAQ&usg=AFQjCNGufLs5F7cb2oPtkBSmpFb1q7Qvow", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "The History of Bread - Roman Bread and Greek Bread | Doves Farm", "rank": 11, "snippet": "Roman Bread Baking flourished in the Roman Empire from as early as 300BC \nbut it wasn't until 168BC that the first Bakers Guild was formed, within 150 years\u00a0...", "link": "https://www.dovesfarm.co.uk/about/the-history-of-bread/the-history-of-bread-roman-bread-and-greek-bread/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCBswAg&usg=AFQjCNHDgZjWCZ-iUSC_OiqiUjAR7FQtbQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Bread Matters", "rank": 12, "snippet": "Find the UK's most authoritative breadmaking courses, browse our selection of \nbreadmaking equipment and buy signed copies of the award winning Bread\u00a0...", "link": "http://www.breadmatters.com/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCB8wAw&usg=AFQjCNEDw_-62sAeIAHQvZvN7jhBKh8lZQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Bread Angels - Own your own home baking business", "rank": 13, "snippet": "Find good bread locally. Set up your own home baking business. Change your \nworld through good bread.", "link": "http://breadangels.com/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCCMwBA&usg=AFQjCNFpx5j3gN6VIkEizq1TYZJDf8KgCQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Bread - ASDA Groceries", "rank": 14, "snippet": "ASDA Extra Special Farmhouse Sliced White Bread New Add to shopping list. \n800G. new!ASDA Extra Special Farmhouse Sliced White Bread. (2). Close. Sorry.", "link": "http://groceries.asda.com/aisle/bakery/bread/910000975414&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCCcwBQ&usg=AFQjCNFrSz_FvCb_2Z1JwDltCzRygmzqKQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Bread | Life and style | The Guardian", "rank": 15, "snippet": "Recipes, reviews and food commentary on bread. ... Letters: There is not a single \nbread called sourdough, and it isn't sour unless you set out to make it that way.", "link": "http://www.theguardian.com/lifeandstyle/bread&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCCswBg&usg=AFQjCNGd_EOctDAxVHtLrNmMN6My42d6jQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "Real Bread Week - Sustain", "rank": 16, "snippet": "The Real Bread Week (14-22 May 2016) is the annual celebration of Real Bread \nand the people who make it.", "link": "http://www.sustainweb.org/realbread/national_real_breadmaker_week/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCC8wBw&usg=AFQjCNHhGMCrAZgJGvF7ztlyH6kFoAtMYQ", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "About Real Bread - Sustain", "rank": 17, "snippet": "Real Bread has nothing to hide. It is made with simple ingredients - only flour, \nwater, yeast and salt - and no artificial additives.", "link": "http://www.sustainweb.org/realbread/what_is_real_bread/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCDMwCA&usg=AFQjCNFoSeW2tRdz1gXNNfjDDjY9-rgyRw", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "BREAD COLLECTIVE", "rank": 18, "snippet": "BREAD IS AN AWARD-WINNING DESIGN COLLECTIVE BASED IN EAST \nLONDON. We specialise in graphic design, typography, art direction, hand \npainted\u00a0...", "link": "http://www.breadcollective.co.uk/&sa=U&ved=0ahUKEwiW5Pro9KHMAhVBC8AKHZZzCBQ4ChAWCDcwCQ&usg=AFQjCNGEV4KeaC1bJ93UzFoOaQDCF544gg", "estimated": 2324000000, "keyphrase": "bread"}
{"title": "The Thoughtful Bread Co. | Award-winning eco-artisan bakery", "rank": 19, "snippet": "Welcome to The Thoughtful Bread Company. An award-winning eco-artisan \nbakery based in Bath, South West England producing hand-crafted bread from \nlocal\u00a0...", "link": "http://www.thethoughtfulbreadcompany.com/&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCBQwAA&usg=AFQjCNHFoxkgzsVJ9z_ezyaN1LAP90O6aw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "I Am Bread - Bossa Studios", "rank": 20, "snippet": "3 Sep 2015 ... The beautiful story of one slice of bread's epic and emotional journey as it \nembarks upon a quest to become toasted. Available now on Steam!", "link": "http://www.iambreadgame.com/&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCBgwAQ&usg=AFQjCNHNENhC8v_slLagyknKNQTklMYO3g", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bread - Waitrose", "rank": 21, "snippet": "Buy Bread online from Waitrose today and explore our wide range of high quality \nBakery. Free delivery - T&amp;Cs apply.", "link": "http://www.waitrose.com/shop/Browse/Groceries/Bakery/Bread&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCB0wAg&usg=AFQjCNFkpcuBvCYN5SK-aozoWCsmJ4cAEw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bristol's Award-winning artisan bakery - Hand made bread in Bristol", "rank": 22, "snippet": "Independent artisan baker in South Bristol, using organic flour, slow fermentation \nand traditional methods.", "link": "http://www.marksbread.co.uk/&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCCAwAw&usg=AFQjCNGkFwpnUEpSIuiS2yupT5gktisRMA", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "The Bread Factory - Wholesale Bakery Supplier of Artisan ...", "rank": 23, "snippet": "We make bread as it was, hundreds of years ago. With responsibly sourced \ningredients, time to let the good flavours develop and made without fuss.", "link": "http://www.breadltd.co.uk/&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCCQwBA&usg=AFQjCNHko5NfuMJ8Kg41vghBIy-4YUayOw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Paul Hollywood's Bread: Amazon.co.uk: Paul Hollywood ...", "rank": 24, "snippet": "Buy Paul Hollywood's Bread by Paul Hollywood (ISBN: 9781408840696) from \nAmazon's Book Store. Free UK delivery on eligible orders.", "link": "https://www.amazon.co.uk/Paul-Hollywoods-Bread-Hollywood/dp/1408840693&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCCgwBQ&usg=AFQjCNEF7l-jzhr2E6VJaRemm8FTIFnsqg", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bread (TV Series 1986\u20131991) - IMDb", "rank": 25, "snippet": "Details of the cast and crew, links and comments from viewers.", "link": "http://www.imdb.com/title/tt0090402/&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCCswBg&usg=AFQjCNGCajKqRETQ6Zdrat-ckLbF58VD0A", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bread Recipes: Onion Bread, Pizza, Focaccia - Great British Chefs", "rank": 26, "snippet": "Browse a stunning collection of bread recipes. From pizza bread and focaccia to \nonion bread, malt bread, sun-dried tomato bread and olive bread.", "link": "http://www.greatbritishchefs.com/collections/bread-recipes&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCDAwBw&usg=AFQjCNFZ_VGXzN1b3IzJXR89Ztmo0LGvCw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bread - Stardew Valley Wiki", "rank": 27, "snippet": "13 Apr 2016 ... Bread is a cooked dish. It is prepared using the kitchen inside a second or third \nstage farmhouse. It is also available at The Saloon for\u00a0...", "link": "http://stardewvalleywiki.com/Bread&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCDQwCA&usg=AFQjCNEi3b2cfKTSb1NsQXPBUbAt1Nu3Mw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Bread - Bakery - Groceries - Tesco Groceries", "rank": 28, "snippet": "Products 1 - 20 of 209 ... Hovis Soft White Medium Bread 800G ... Warburtons Toastie Sliced White Bread \n800G ... Hovis Wholemeal Medium Bread 800G.", "link": "http://www.tesco.com/groceries/product/browse/default.aspx%3FN%3D4292930214%26Ne%3D4294793660&sa=U&ved=0ahUKEwiWrp7s9KHMAhVNFMAKHc8qDiI4FBAWCDgwCQ&usg=AFQjCNGWcGEUgd16fVKBQ8SHwbu7KUkqgw", "estimated": 3324000000, "keyphrase": "bread"}
{"title": "Creating fresh competitive advantage - Bread PR Aberdeen", "rank": 29, "snippet": "We help you define brand position and direction, then deliver imaginative media, \nmarketing and employee engagement campaigns for PR and investor\u00a0...", "link": "http://www.breadpr.com/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCBQwAA&usg=AFQjCNGOrbVFxUbEGkccu6QW79xMhysH4w", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Bread Recipes in The Bread Kitchen", "rank": 30, "snippet": "Making perfect bread is not as difficult as you may think. All you need are some \ngood ingredients, a few tools, my helpful bread recipes and patience!", "link": "http://www.thebreadkitchen.com/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCBgwAQ&usg=AFQjCNHg0Rniflu1-HKrd6q-fqZ3gfQ6xQ", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Vogel's Healthy, Seeded Bread, Keep Exploring, Toast Ticket", "rank": 31, "snippet": "Vogel's bread makes the tastiest toast as it's crammed to bursting with seeds &amp; \ngrains. Keep Exploring , find a Toast Ticket and win!", "link": "http://vogelsbread.co.uk/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCBwwAg&usg=AFQjCNHw36cfXgzjK5a7fjErQ-FF08lKRg", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Bread Making Courses London - Learn How to Start a Home Baking ...", "rank": 32, "snippet": "Bread Making Courses in West London and Learn How to Start a Home Baking \nBusiness with Virtuous Bread. Team Building Events with Bread.", "link": "http://www.virtuousbread.com/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCCAwAw&usg=AFQjCNGhaABmPM4aeCALBT9cmdI4brz6zw", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "History of Bread 1", "rank": 33, "snippet": "Bread, in one form or another, has been one of the principal forms of food for man \nfrom earliest times. The trade of the baker, then, is one of the oldest crafts in\u00a0...", "link": "http://www.botham.co.uk/bread/history1.htm&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCCQwBA&usg=AFQjCNGwoK4z7Ysne130O6C04Iq7DooNYA", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Advanced Bread Class \u2013 E5 Bakehouse", "rank": 34, "snippet": "Following on from our original bread class, the e5 bakehouse 'advanced bread \nclass' offers you the opportunity to consider various aspects of sourdough baking\n\u00a0...", "link": "http://e5bakehouse.com/classes/advanced-bread-class/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCCgwBQ&usg=AFQjCNHGAlLjqlyw0NGZUNBypW3qneVXqw", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Home - Leeds Bread Co-operative", "rank": 35, "snippet": "Bakery making artisan Sourdough and Slowly Fermented bread for the good \npeople of Leeds and surrounds. Markets and bread subs.", "link": "http://leedsbread.coop/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCCwwBg&usg=AFQjCNETChCXrMb88x3h3OQORRdKPr-yqA", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Bread Recipes - from Delia Online", "rank": 36, "snippet": "Bread Recipes. Bread really is easy to make, as long as you follow a few simple \nrules. Get it right and you'll never look back - or want to eat shop-bought loaves\u00a0...", "link": "http://www.deliaonline.com/recipes/type-of-dish/bread&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCDAwBw&usg=AFQjCNHlT6O7DDfTQGs2E2DLEv1HsqUMQA", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "the little bread pedlar | handmade croissants and brownies ...", "rank": 37, "snippet": "The Little Bread Pedlar is open directly to the public on Saturdays from 9am until \n2pm alongside Coleman Coffee Roasters and other wholesale producers at\u00a0...", "link": "https://lbpedlar.com/&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCDQwCA&usg=AFQjCNEVS8Ji6EBr_ZDSykn2UOdxVgzCGw", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "High Protein Breads - Up To 30g Protein Per Serving - Dr Zaks", "rank": 38, "snippet": "Protein Bread, Pasta &amp; Rice. Missed bread and pasta? Well, miss it no more \nbecause they're back on the menu! Our huge range of breads, pastas, wraps and\n\u00a0...", "link": "http://www.musclefood.com/high-protein-snacks-1/protein-bread.html&sa=U&ved=0ahUKEwiWm4Lv9KHMAhUjAsAKHaeWAJk4HhAWCDcwCQ&usg=AFQjCNEhBoHm557vr3APMQJOo0N91HkUug", "estimated": 4324000000, "keyphrase": "bread"}
{"title": "Bread and a Dog | Fashion / Culture | Phaidon Store", "rank": 39, "snippet": "A quirky, photographic exploration of two beloved subjects: breakfasts and dogs. \nTaps into the popularity of two of Instagram's hottest trends: food and pet\u00a0...", "link": "http://www.phaidon.com/store/fashion-culture/bread-and-a-dog-9780714870489/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCBQwAA&usg=AFQjCNGtRd8sDHuq6VPn57N9rFqckrNXkQ", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "Bread - GAIL's Bakery", "rank": 40, "snippet": "Caramelised garlic bread. We caramelise whole cloves of garlic and fold the \ndough around them to create a richly perfumed loaf. Perhaps not the best choice \nfor\u00a0...", "link": "http://gailsbread.co.uk/our-food/bread/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCBcwAQ&usg=AFQjCNHR6Jvtu4IYBy-z6snjU6iwdtSsmQ", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "British Museum - Bread recipe", "rank": 41, "snippet": "In AD 79, a baker put his loaf of bread into the oven.\n ... The British Museum asked Giorgio Locatelli to recreate the recipe as part of his culinary investigations for Pompeii Live.\n ... Carbonised loaf of bread, AD 79, Roman, Herculaneum.", "link": "http://www.britishmuseum.org/whats_on/past_exhibitions/2013/pompeii_and_herculaneum/bread_recipe.aspx&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCBswAg&usg=AFQjCNHBf2Fkj60JxhM4uZ1VjisSKz39ww", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "BURNS THE BREAD... burnsthebread.co.uk... The finest cakes ...", "rank": 42, "snippet": "Producers of the finest freshly hand-made pastries, cakes, bread, rolls, croissants\n, muffins, and other baked goods. Located in Glastonbury, England.", "link": "http://www.burnsthebread.co.uk/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCB8wAw&usg=AFQjCNFIX7B-_z77ZbeA9uAIyWIsmqV5iA", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "bread Meaning in the Cambridge English Dictionary", "rank": 43, "snippet": "bread meaning, definition, what is bread: a food made from flour, water, and \nusually yeast, mixed together and baked: . Learn more.", "link": "http://dictionary.cambridge.org/dictionary/english/bread&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCCMwBA&usg=AFQjCNGtUCIf1az8TbSvOvaK2BFrn_m8IA", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "Bread+Butter Glasgow", "rank": 44, "snippet": "Bar and restaurant. Includes menus, events and directions.", "link": "http://breadandbutterglasgow.co.uk/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCCcwBQ&usg=AFQjCNFn-8k627EpVUUamf34wWGhExIvag", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "Bread Recipes | BakingMad.com", "rank": 45, "snippet": "Bread Recipes: Browse our wide selection of bread recipes, including bread roll \nrecipes, perfect white bread, delicious wholemeal bread, and even our fruity\u00a0...", "link": "https://www.bakingmad.com/bread-recipes/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCCswBg&usg=AFQjCNEeUJJ7efc7AzBVX2J0vpKR1lYO4w", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "Bakery - Bread | Greggs", "rank": 46, "snippet": "From white rolls to sliced wholemeal loaves, our bread is freshly baked every day \nin our regional bakeries. Greggs, Always fresh. Always tasty.", "link": "https://www.greggs.co.uk/menu/bread/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCC8wBw&usg=AFQjCNEcCw20J5fRGJbk7BeMAUVRbzlklw", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "The Bread &amp; Roses Theatre - Home", "rank": 47, "snippet": "Innovative and award-winning fringe pub theatre in Clapham, South London. \nOffering a diverse quality program for audiences and box office splits for visiting\u00a0...", "link": "http://www.breadandrosestheatre.co.uk/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCDMwCA&usg=AFQjCNFW6UO2AEmsIvLTiVCyAs-hEL3VKQ", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "PETER COOKS BREAD", "rank": 48, "snippet": "A new bakery set in the foot of the Malvern Hills. On a mission to spread the joys \nof Real Bread with Ledbury and beyond.", "link": "http://www.petercooksbread.co.uk/&sa=U&ved=0ahUKEwjai_vx9KHMAhUoD8AKHXL_AVw4KBAWCDcwCQ&usg=AFQjCNG-gDDM_TwxDxiDWWpLLk841F7snw", "estimated": 5324000000, "keyphrase": "bread"}
{"title": "The Bread &amp; Roses Pub - About Us", "rank": 49, "snippet": "We attract a broad cross section of customers and host a variety of eclectic events \neach months including meetings, functions and parties in our Function or\u00a0...", "link": "http://www.breadandrosespub.com/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCBQwAA&usg=AFQjCNFMpCREuKSSKY1UpnLY_QB9taaWzQ", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Bread and Jam: Runaway Dress", "rank": 50, "snippet": "Bread and Jam: Super little tiny dresses from the UK.", "link": "http://ilovebreadandjam.com/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCBgwAQ&usg=AFQjCNEt_0YDfp7TmaOfNnBzFnep6iwlGg", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Hovis | Go On", "rank": 51, "snippet": "Wholewheat bread; offers company profile, details of products, recipes, and \ncontacts. Located in Windsor, England.", "link": "http://www.hovis.co.uk/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCBwwAg&usg=AFQjCNHkRaAtrXw4z93VEAoBFzmGWIDbig", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "LoveBread CIC | Real Bread has nothing to hide", "rank": 52, "snippet": "LoveBread CIC is a community supported bakery, aiming to bring the many \nbenefits of baking real bread to Brighouse and Calderdale communities.", "link": "http://lovebread.org.uk/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCCAwAw&usg=AFQjCNFfrNevah5S6h4gyPlulYbTHkld8w", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Bread and Goose", "rank": 53, "snippet": "BREAD &amp; GOOSE create engaging journeys through non-traditional theatre \nspaces, placing the audience at the centre of the story. Our work is curious, \nplayful,\u00a0...", "link": "http://www.breadandgoose.co.uk/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCCQwBA&usg=AFQjCNFrmg8N68KAMWcLtGq6ppqV1TVbfQ", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Artisan Bread Organic: Gluten-Free and Wheat-Free Bread | Artisan ...", "rank": 54, "snippet": "Artisan Bread Organic. ... Artisan Bread Organic - Join us on Facebook ... ABO \nbread breaks all moulds with a host of innovative products \u2013 this is not something\n\u00a0...", "link": "http://www.artisanbread-abo.com/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCCgwBQ&usg=AFQjCNHK86TThqQS-_n7IkQI1H3J1hhKlA", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Beyond Bread", "rank": 55, "snippet": "Beyond Bread Bakery is a culinary pioneer who \u2013 through a range of naturally \ngluten-free foods \u2013 inspires you on a journey to discover new, yet familiar tastes.", "link": "http://www.beyondbread.co.uk/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCCwwBg&usg=AFQjCNHWMWKblZ3mxqOtr2SfvwR1WLTYvw", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Supermarket denies selling burnt bread: 'It's just well-fired' - Telegraph", "rank": 56, "snippet": "22 Mar 2016 ... Shoppers at Sainbury's have been perturbed by the appearance of what they \nclaim is burnt bread on the supermaket's shelves. Labelled \"Well\u00a0...", "link": "http://www.telegraph.co.uk/news/newstopics/howaboutthat/12201253/Supermarket-denies-selling-burnt-bread-Its-just-well-fired.html&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCDAwBw&usg=AFQjCNGBrfh2efVrbmKVNe5NocZNW2dlOg", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "Should you cut out bread to stop bloating? - Live Well - NHS Choices", "rank": 57, "snippet": "Find out how cutting out bread and other wheat-based foods like pasta, cereals, \ncakes and biscuits can ease bloating and other digestive symptoms if you are\u00a0...", "link": "http://www.nhs.uk/Livewell/digestive-health/Pages/cutting-out-bread.aspx&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCDMwCA&usg=AFQjCNFwMwomrQwZ_STFoDaEbPWDnXejsw", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "World Bread Awards: Home", "rank": 58, "snippet": "Exciting awards celebrating the art of bread baking - open to professional and ... \n23 hours, 59 minutes and 38 seconds left to enter World Bread Awards 2016.", "link": "http://www.worldbreadawards.com/&sa=U&ved=0ahUKEwjChcP19KHMAhWpCsAKHXK1Cr84MhAWCDcwCQ&usg=AFQjCNEByMzyT2ydAKU88JXxCINQOEoPRA", "estimated": 6324000000, "keyphrase": "bread"}
{"title": "MHOR BREAD - Monachyle Mhor Hotel", "rank": 59, "snippet": "MHOR Bread. Why should you have to pay more for organic food? All food \nshould be safe and good for you. This is the basic premise on which all the Mhor\n\u00a0...", "link": "http://mhor.net/mhor-bread/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCBQwAA&usg=AFQjCNFO5FS2rOM5xSymz_azCu8XjNSxHQ", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "The Bread Kitchen - YouTube", "rank": 60, "snippet": "If you want to learn how to make your own bread, or are looking for inspiration to \nmake something different, you have come to the right place! The Bread Kitc...", "link": "https://www.youtube.com/user/TheBreadKitchen&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCBgwAQ&usg=AFQjCNHNElyh5MqdS_4r0VCm11D8EMDHcA", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "Andy's Bread - realbread made in Llanidloes, Mid-WalesAndy's ...", "rank": 61, "snippet": "Artisan bread made in the kitchen of the Old Mill Bar in Llanidloes, Powys, Mid-\nWales. Sourdough wheat, rye breads, tin loaves, patisserie available.", "link": "http://www.andysbread.co.uk/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCBwwAg&usg=AFQjCNEUoNQI7aRq6tERVtGuG0JYxL5_Yw", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "PAUL : French Family Bakery and Patisserie since 1889 - OUR ...", "rank": 62, "snippet": "Baguettes &gt; Discover \u00b7 Baguettes \u00b7 Pain Malt C\u00e9r\u00e9ales \u00b7 Les Fl\u00fbtes et Baguettes \u00b7 \nBaguette Charlemagne 250g \u00b7 Mini Fougasses 100g \u00b7 Small Breads \u00b7 Les\u00a0...", "link": "http://www.paul-uk.com/shop/en-UK/Category/Bread_1&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCCAwAw&usg=AFQjCNHXMYkMlfz6zgeCuweZSWRwQvFsQg", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "The Slow Bread Company - Home", "rank": 63, "snippet": "We make bread that we mix and then knead and mould by hand, from locally-\nmilled flour and our natural leaven, proved and fermented for 24 hours, creating a\n\u00a0...", "link": "http://www.slowbreadcompany.co.uk/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCCQwBA&usg=AFQjCNECzQdFS7sNBAPNgzqOONDdSHMwZA", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "The Bread Oven - Warwick SU", "rank": 64, "snippet": "Students. If you are a current student at the University of Warwick, click the link \nbelow to log in using your IT Services username and password. Student Login\u00a0...", "link": "https://www.warwicksu.com/breadoven/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCCgwBQ&usg=AFQjCNGAHgX2xA-T25XNHqsPmFvJsDsZFQ", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "Vicky's Bread: Home", "rank": 65, "snippet": "Welcome to Vicky's Bread. Our beautiful french artisan breads include the classic \nbaguette, multigrain, rustic Bordelais sourdough and spelt sourdough. We also\u00a0...", "link": "http://www.vickysbread.co.uk/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCCswBg&usg=AFQjCNE8J6NR_7WM4h5gRTg20DYbgUMJWw", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "Deliciously soft, quality bread just 75p | Co-operative Food", "rank": 66, "snippet": "Pick up our Loved by us sliced bread in store, with four varieties to choose from at \nonly 75p a loaf - we know bread is important!", "link": "http://www.co-operativefood.co.uk/groceries/about-our-food/our-bread/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCC8wBw&usg=AFQjCNGn_vRYUt3P8r71Fst5RsOxwHQxUw", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "Beer Bread Recipe | Gordon Ramsay Recipes", "rank": 67, "snippet": "These mini bread loaves are a kind of English take on Irish soda bread, using the \nfizziness of the beer as the raising agent. Read the recipe here.", "link": "https://www.gordonramsay.com/gr/recipes/beer-bread/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCDIwCA&usg=AFQjCNG7NNZkk5nn9724gHqTft-ugELkUQ", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "Emma's Bread | Real bread made using traditional methods", "rank": 68, "snippet": "Emma's Bread is real bread made using traditional methods resulting in a flavour \nand texture to satisfy the stomach and the soul. Specialities include rye, white\u00a0...", "link": "http://www.emmasbread.co.uk/&sa=U&ved=0ahUKEwie0Nn49KHMAhXlLcAKHSRuDCM4PBAWCDUwCQ&usg=AFQjCNHL6hhtdWueOT74HmUo0kOHg6Q54Q", "estimated": 7324000000, "keyphrase": "bread"}
{"title": "M&amp;S scraps basic bread for fibre-filled alternatives after fall in sales ...", "rank": 69, "snippet": "10 Jan 2016 ... In future, the company says all of its bread and rolls, including standard white \nloaves, will be baked with extra fibre. It comes after they already\u00a0...", "link": "http://www.dailymail.co.uk/news/article-3393142/Is-toast-simple-white-loaf-M-S-scraps-basic-bread-fibre-filled-alternatives-fall-sales.html&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCBQwAA&usg=AFQjCNEcxl83PvNuZXPxUC7DZYhsM9CxCg", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Wells Banana Bread Beer - Charles Wells", "rank": 70, "snippet": "Available as a draught seasonal cask beer, Wells Banana Bread Beer can be \nfound on the bar and, in its popular bottle format, in all leading supermarkets.", "link": "http://www.charleswells.co.uk/our-company/our-products/wells-banana-bread-beer/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCBcwAQ&usg=AFQjCNH4dRzktXwriidgko3HuVJnkfUvrw", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Breads Etcetera (@BreadsEtc) | Twitter", "rank": 71, "snippet": "The latest Tweets from Breads Etcetera (@BreadsEtc). Modern British Urban \nBakery &amp; Cafe Specialising in Sourdough Breads. DIY Toast and Yummy Breakie\n.", "link": "https://twitter.com/breadsetc&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCBswAg&usg=AFQjCNFhRIJBr3KTLSayaQwFkU0wEaVg6w", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Triple Seeded Sandwich Bread | Bread &amp; Rolls - Genius Gluten Free", "rank": 72, "snippet": "Baked with poppy, linseed and sunflower seeds for a tasty crunch, our Triple \nSeeded Sandwich Loaf makes a delicious change to everyday bread. Our new\u00a0...", "link": "http://www.geniusglutenfree.com/en_GB/p/TripleSeededSandwichBread&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCB8wAw&usg=AFQjCNGRgRIjZG49tgGrJHIZSYj5P-CZHg", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Allinson - Wholesome Baking", "rank": 73, "snippet": "At Allinson we have a passion for making delicious wholemeal bread. A tradition \nstarted by our visionary founder, Thomas Allinson, a very modern Victorian.", "link": "http://www.allinsonbread.com/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCCMwBA&usg=AFQjCNEePnsmvakRSmhdXgPKXTnqrhP83Q", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "House of Bread - Home", "rank": 74, "snippet": "About Us.... House of Bread (HOB) is an organisation that offers a home-cooked \nmeal for vulnerable and homeless people in the Stafford area. more.", "link": "http://www.hobstafford.co.uk/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCCcwBQ&usg=AFQjCNGvwpCxtcZS11xKIdSdxQw6mewP6g", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Bread &amp; dairy - IKEA", "rank": 75, "snippet": "Bread &amp; dairy. ... Muesli with berries. \u00a32.50. /0.5 kg \u00b7 BR\u00d6D MJUKKAKA soft \nwheat bread, frozen Net weight: 200 g. BR\u00d6D MJUKKAKA. soft wheat bread, \nfrozen.", "link": "http://www.ikea.com/gb/en/catalog/categories/departments/food/25212/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCCswBg&usg=AFQjCNFGvzo9_hevkSFioBuj7GBdyWdChg", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Bread and Roses", "rank": 76, "snippet": "The Alliance of Radical Booksellers (ARB) is delighted to announce the shortlist \nfor the Bread and Roses Award for Radical Publishing 2016. Now in its fifth year\n\u00a0...", "link": "http://www.bread-and-roses.co.uk/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCC8wBw&usg=AFQjCNGjlam0H7eDnQp91bxXxWfDX7GSIA", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Burgen Bread - Deliciously Healthy, Seeded Breads", "rank": 77, "snippet": "At Burgen we bake our breads with nutritious ingredients so that they taste really \ngood and are good for your health.", "link": "http://www.burgenbread.com/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCDMwCA&usg=AFQjCNEDbgUcXzEB9hKmAmRwgIOlI125kw", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Bread &amp; Roses Plymouth", "rank": 78, "snippet": "A community arts hub selling organic and fairtraide food and drinks. We support \nlocal music and the arts.", "link": "http://www.breadandrosesplymouth.co.uk/&sa=U&ved=0ahUKEwjxnpz89KHMAhWCDMAKHQZHDlg4RhAWCDcwCQ&usg=AFQjCNGa1itKa8G-q6jG1SnVmc06frXBmw", "estimated": 8324000000, "keyphrase": "bread"}
{"title": "Authentic Bread Company Organic", "rank": 79, "snippet": "Using the finest organic ingredients, we at the Authentic Bread Company are \nstriving to produce a taste and texture that you won't find anywhere else.", "link": "http://www.authenticbread.co.uk/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCBQwAA&usg=AFQjCNGLcFGEHWiwi2aMXECWJzlPjo3XVw", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Catering Company London - Bread &amp; Honey Bread &amp; Honey", "rank": 80, "snippet": "Corporate catering, occasion catering and events production company operating \nin and around London. Visit us online to find out more about our services.", "link": "http://www.breadandhoneyevents.co.uk/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCBgwAQ&usg=AFQjCNGZ-N_5ZY_v0YcDyYunViYVxHDQFA", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Brick House Bread", "rank": 81, "snippet": "Hello, we're Brick House, a small but perfectly formed sourdough bakery based in \nEast Dulwich just off Peckham Rye Common.", "link": "http://www.brickhousebread.com/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCBwwAg&usg=AFQjCNEq0N1vOmYgID2_YVkvKgUjL56JOw", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "The Bread Shop: Home", "rank": 82, "snippet": "Welcome to Breadshop.co.uk - home of fantastic continental breads. With stores \nin London, and supplying major London stores such as Selfridges and\u00a0...", "link": "http://www.breadshop.co.uk/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCCAwAw&usg=AFQjCNGDD3HKw_0XhUYRoQGba3OHNEr7pQ", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Bread - Netmums", "rank": 83, "snippet": "Here's a recipe for making bread dough - you can make a simple loaf of bread or \ntry some rolls. Get the kids involved in baking too! Making bread is a very\u00a0...", "link": "http://www.netmums.com/recipes/bread&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCCQwBA&usg=AFQjCNG-WkLJoAb8aoZBM_ygRsI9Ycbqbw", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Bread Magazine - Facebook", "rank": 84, "snippet": "Bread Magazine. 8839 likes \u00b7 296 talking about this. Micro magazine for people \nwho love and make great bread. Subscribe at https://bread-magazine.com/", "link": "https://www.facebook.com/interested.bread&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCCkwBQ&usg=AFQjCNH4UdIlqgjngnhXBU5CZY4FzYmAPw", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Bread &amp; Jam", "rank": 85, "snippet": "Happy things to give as gifts or to treasure for yourself.", "link": "http://www.wearebreadandjam.co.uk/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCC0wBg&usg=AFQjCNFdae0NTkW5CTCw5FQewW80b7606Q", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "Bread and Butter Marketing: Home", "rank": 86, "snippet": "Home Page of Bread and Butter Marketing, a Certified Google Adwords Partner \ncompany providing online marketing and social media integration advice.", "link": "http://breadandbuttermarketing.co.uk/&sa=U&ved=0ahUKEwjIkb3_9KHMAhXCFsAKHdOAC1E4UBAWCDEwBw&usg=AFQjCNEh-iJ7RHHI6bqgkntE3CQ1_BiSbA", "estimated": 9324000000, "keyphrase": "bread"}
{"title": "bread &amp; wine spitalfields - St. John", "rank": 87, "snippet": "Find Us. 94-96 Commercial Street London E1 6LZ. St. JOHN BREAD and Wine is \nlocated across the road from Spital